### ISSUE TITLE
Issue sorting based on _running tag

### ISSUE THREAD

**Issue by jinchang** [muhrin/mincepy_gui#11]
I just faced this error meesage. Is this expected?

<img width="884" alt="Screen Shot 2020-05-29 at 6 46 56 PM" src="https://user-images.githubusercontent.com/605756/83284389-eb40f000-a1dc-11ea-8c09-a15b2eeb60df.png">

**Comment by muhrin** [comment]
Ah that's cool!  Means we're moving to truly big-data :)

I think MongoDB provides a fairly easy fix for this, but I need to test it out.  That's just on our standard `maibat` repo sorting all `VaspRun`s, right?

**Comment by jinchang** [comment]
That's right! 🙂

**Comment by muhrin** [comment]
Ok, I believe I have a fix.  Would you mind testing for me when you get a chance?  I've tried the GUI and it seems fine now, but it'd be good to get confirmation.  Steps:

1. Clone `mincepy`: `git clone https://github.com/muhrin/mincepy.git` (if you don't already have it)
2. `cd mincepy`, then, `pip install -e .` (make sure you're on develop)
3. Try the GUI again, see if it's fixed.

**Comment by muhrin** [comment]
I'm assuming that this is fixed.  Please re-open if this is not the case.
