### ISSUE TITLE
Enhancement request: Query for object ID's

### ISSUE THREAD

**Issue by atygesen** [muhrin/mincepy_gui#12]
It would be nice if we could have a box specialized for querying a particular object ID.

Slightly more advanced, could be to add a drop-down menu, where you could add a particular key-value filter, and possibly add multiple of them. The current querying is not particularly human-readable friendly, I'm afraid :smiley:

**Comment by muhrin** [comment]
Yes, good idea.  I'll plan adding this in.

**Comment by muhrin** [comment]
Done.  Released in v0.3.4.
